//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarketPlace.ExistingDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderLineItem
    {
        public int Id { get; set; }
        public int LineItemId { get; set; }
        public int OrderId { get; set; }
        public bool IsDeleted { get; set; }
        public string CreatedBy { get; set; }
        public string CreatedOn { get; set; }
        public string LastModifiedBy { get; set; }
        public System.DateTime LastModifiedOn { get; set; }
    
        public virtual LineItem LineItem { get; set; }
        public virtual Order Order { get; set; }
    }
}
